[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build:backend"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"