name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - 'shared/**'
      - '.github/workflows/deploy-frontend.yml'
      - 'package.json'
      - 'vite.config.ts'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Frontend
        env:
          VITE_API_URL: ${{ secrets.BACKEND_URL }}
        run: |
          npm run build:frontend
          echo > dist/public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/public
          branch: gh-pages