name: Deploy Backend to Railway

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - 'shared/**'
      - '.github/workflows/deploy-backend.yml'
      - 'package.json'
      - '.railway.toml'
      - 'Procfile'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up