name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - 'shared/**'
      - 'src/**'
      - 'public/**'           
      - 'scripts/**'           
      - 'attached_assets/**'  
      - '.env*'               
      - '.github/workflows/deploy-frontend.yml'
      - 'package.json'
      - 'vite.config.ts'
      - 'build-frontend.sh'   
      - 'tsconfig.json'       

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Atualizado para v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Atualizado para v4
        with:
          node-version: '20'
          cache: 'npm' 

      - name: Install dependencies
        run: npm ci # Usando 'ci' para consistência, certifique-se que package-lock.json está no repo

      - name: Run directory sync script
        run: |
          echo "==> Verificando estrutura de diretórios antes da sincronização:"
          find . -type d -not -path "*/node_modules/*" -not -path "*/dist/*" -not -path "*/.git/*" | sort

          echo "==> Definindo permissões do script de sincronização:"
          chmod +x ./scripts/sync-src-folders.sh
          
          echo "==> Executando script de sincronização src/ para client/src/:"
          ./scripts/sync-src-folders.sh

      - name: Build Frontend
        env:
          VITE_API_URL: https://web-production-76420.up.railway.app
          VITE_GOOGLE_PLACES_API_KEY: ${{ secrets.VITE_GOOGLE_PLACES_API_KEY }}
        run: |
          echo "==> Verificando conteúdo de alterações cruciais antes do build:"
          
          echo "==> Conteúdo de client/src/App.tsx (contém botão Saviana):"
          cat client/src/App.tsx || echo "ERRO: Arquivo não encontrado!"
          
          echo "==> Conteúdo de client/src/components/GeolocationStatus.tsx (contém indicador visual):"
          cat client/src/components/GeolocationStatus.tsx || echo "ERRO: Arquivo não encontrado!"
          
          echo "==> Conteúdo de client/src/lib/geo-fallback.ts (contém variável de ambiente para API):"
          cat client/src/lib/geo-fallback.ts || echo "ERRO: Arquivo não encontrado!"
          
          echo "==> Iniciando build do Vite..."
          # Removida a flag --force inválida. --debug ainda está presente.
          npx vite build --base=/Saviana/ --debug
          echo "==> Build do Vite concluído."
          
          echo "==> Verificando o conteúdo de dist/public após o build:"
          echo "Listando conteúdo de dist/public:"
          ls -R dist/public 
          
          echo "Conteúdo do index.html gerado em dist/public/index.html:"
          if [ -f dist/public/index.html ]; then
            grep -E 'rel="stylesheet" href="/Saviana/assets/|src="/Saviana/assets/' dist/public/index.html
          else
            echo "AVISO: dist/public/index.html não encontrado."
          fi
          
          echo "==> Verificando presença dos componentes no bundle JavaScript:"
          if [ -f dist/public/assets/*.js ]; then
            echo "Verificando presença do botão Saviana no bundle JS:"
            grep -i "saviana" dist/public/assets/*.js || echo "AVISO: Botão 'Saviana' não encontrado no bundle!"
            
            echo "Verificando presença do componente GeolocationStatus no bundle JS:"
            grep -i "geolocationstatus" dist/public/assets/*.js || echo "AVISO: Componente 'GeolocationStatus' não encontrado no bundle!"
            
            echo "Verificando variáveis de ambiente no bundle JS:"
            grep -i "VITE_GOOGLE_PLACES_API_KEY" dist/public/assets/*.js || echo "AVISO: Variável VITE_GOOGLE_PLACES_API_KEY não encontrada no bundle!"
          else
            echo "AVISO: Arquivos JavaScript não encontrados em dist/public/assets/"
          fi
          
          echo "==> Verificação do index.html e assets concluída."

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/public 
