name: TypeScript Check

on:
  push:
    branches: [ main ]
    paths:
      - '**.ts'
      - '**.tsx'
      - 'package.json'
      - 'tsconfig.json'
      - 'tsconfig.ci.json'
      - 'scripts/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.ts'
      - '**.tsx'
      - 'package.json'
      - 'tsconfig.json'
      - 'tsconfig.ci.json'
      - 'scripts/**'

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Prepare UI Components
        run: |
          chmod +x scripts/fix-components-for-typechecking.sh
          scripts/fix-components-for-typechecking.sh

      - name: Secure TypeScript Check
        run: |
          chmod +x scripts/secure-ci-check.sh
          scripts/secure-ci-check.sh
          
      - name: Check Security Report
        run: |
          echo "⚠️ Verificação de relatório de segurança completa"
          echo "Para qualquer vulnerabilidade detectada, revisar manualmente"