name: TypeScript Check

on:
  push:
    branches: [ main ]
    paths:
      - '**.ts'
      - '**.tsx'
      - 'package.json'
      - 'tsconfig.json'
      - 'tsconfig.ci.json'
      - 'scripts/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.ts'
      - '**.tsx'
      - 'package.json'
      - 'tsconfig.json'
      - 'tsconfig.ci.json'
      - 'scripts/**'

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Prepare UI Components
        run: |
          chmod +x scripts/fix-components-for-typechecking.sh
          scripts/fix-components-for-typechecking.sh

      - name: Setup TypeScript for Shadcn
        run: |
          chmod +x scripts/setup-shadcn-typescript.sh
          scripts/setup-shadcn-typescript.sh
      
      - name: TypeScript Check (excluding UI components)
        run: |
          echo "Running TypeScript check excluding problematic UI components..."
          npx tsc --noEmit --skipLibCheck $(find client/src -name "*.ts" -o -name "*.tsx" | grep -v "client/src/components/ui")